### ISSUE TITLE
Do you accept behance links ?

### ISSUE THREAD

**Issue by kossa** [emmawedekind/developer-portfolios#49]
Hello,

Do you accept behance link ? like https://www.behance.net/kossa

**Comment by wotta** [comment]
If it is your portfolio than there shouldn't be any problem in my opinion.

**Comment by kossa** [comment]
@wotta Yes mine

**Comment by wotta** [comment]
@kossa looks like a solid portfolio. But do you also have a personal website?
If not I would suggest creating a PR with the Behance link. Otherwise, I would send a PR with your personal website.

**Comment by kossa** [comment]
Done ;)
